=== demianbarry/zonales/branches/services/ZonalesSolrClient/src/conf/xml-resources/jaxb/Requerimiento/ZonalesSolrQueryRequerimiento.xsd
<?xml version="1.0" encoding="UTF-8"?>

<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema"
    targetNamespace="http://xml.netbeans.org/schema/ZonalesSolrQueryRequerimiento"
    xmlns:tns="http://xml.netbeans.org/schema/ZonalesSolrQueryRequerimiento"
    elementFormDefault="qualified">
    <xsd:complexType name="parametroType">
        <xsd:all>
            <xsd:element name="clave" type="xsd:string"></xsd:element>
            <xsd:element name="valor" type="xsd:string"></xsd:element>
        </xsd:all>
    </xsd:complexType>
    <xsd:complexType name="parametrosType">
        <xsd:sequence>
            <xsd:element name="parametro" type="tns:parametroType" maxOccurs="unbounded" minOccurs="0"></xsd:element>
        </xsd:sequence>
    </xsd:complexType>
    <xsd:complexType name="contenidoType">
        <xsd:sequence>
            <xsd:element name="query" type="xsd:string"></xsd:element>
            <xsd:element name="sortFields" type="tns:sortFieldsType"></xsd:element>
            <xsd:element name="parametros" type="tns:parametrosType" minOccurs="0"></xsd:element>
        </xsd:sequence>
    </xsd:complexType>
    <xsd:element name="requerimiento">
        <xsd:complexType>
            <xsd:all>
                <xsd:element name="contenido" type="tns:contenidoType"></xsd:element>
            </xsd:all>
        </xsd:complexType>
    </xsd:element>
    <xsd:complexType name="sortType">
        <xsd:attribute name="field" type="xsd:string"/>
        <xsd:attribute name="order" type="xsd:string"/>
    </xsd:complexType>
    <xsd:complexType name="sortFieldsType">
        <xsd:sequence>
            <xsd:element name="sort" type="tns:sortType" minOccurs="0" maxOccurs="unbounded"></xsd:element>
        </xsd:sequence>
    </xsd:complexType>
</xsd:schema>

=== demianbarry/zonales/branches/services/ZonalesSolrClient/src/java/com/zonales/solrclient/ZonalesSolrQueryRequerimiento.xml
<?xml version="1.0" encoding="UTF-8"?>

<!--
    Document   : ZonalesSolrQueryRequerimiento.xml
    Created on : 14 de octubre de 2009, 16:16
    Author     : fep
    Description:
        Purpose of the document follows.
-->

<ns0:requerimiento  xmlns:xsi='http://www.w3.org/2001/XMLSchema-instance'
   xmlns:ns0='http://xml.netbeans.org/schema/ZonalesSolrQueryRequerimiento'
   xsi:schemaLocation='http://xml.netbeans.org/schema/ZonalesSolrQueryRequerimiento ZonalesSolrQueryRequerimiento.xsd'>
    <ns0:contenido>
        <ns0:query></ns0:query>
        <ns0:sortFields>
            <ns0:sort field="" order=""></ns0:sort>
            <ns0:sort field="" order=""></ns0:sort>
            <ns0:sort field="" order=""></ns0:sort>
        </ns0:sortFields>
        <ns0:parametros>
            <ns0:parametro>
                <ns0:clave></ns0:clave>
                <ns0:valor></ns0:valor>
            </ns0:parametro>
            <ns0:parametro>
                <ns0:clave></ns0:clave>
                <ns0:valor></ns0:valor>
            </ns0:parametro>
            <ns0:parametro>
                <ns0:clave></ns0:clave>
                <ns0:valor></ns0:valor>
            </ns0:parametro>
        </ns0:parametros>
    </ns0:contenido>

</ns0:requerimiento>
