=== demianbarry/zonales/branches/services/ZonalesSolrClient/src/conf/xml-resources/jaxb/Respuesta/ZonalesSolrQueryRespuesta.xsd
<?xml version="1.0" encoding="UTF-8"?>

<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema"
    targetNamespace="http://www.zonales.com.ar/schema/ZonalesSolrQueryRespuesta"
    elementFormDefault="qualified" xmlns:tns="http://www.zonales.com.ar/schema/ZonalesSolrQueryRespuesta">
    <xsd:complexType name="resultadoType">
        <xsd:all>
            <xsd:element name="id" type="xsd:integer"></xsd:element>
            <xsd:element name="titulo" type="xsd:string"></xsd:element>
            <xsd:element name="texto" type="xsd:string"></xsd:element>
            <xsd:element name="fecha_publicacion" type="xsd:dateTime"></xsd:element>
        </xsd:all>
        <xsd:attribute name="score" type="xsd:string"/>
    </xsd:complexType>
    <xsd:complexType name="resultadosType">
        <xsd:sequence>
            <xsd:element name="resultado" type="tns:resultadoType" maxOccurs="unbounded"></xsd:element>
        </xsd:sequence>
    </xsd:complexType>
    <xsd:complexType name="contenidoType">
        <xsd:sequence>
            <xsd:element name="resultados" type="tns:resultadosType"></xsd:element>
        </xsd:sequence>
    </xsd:complexType>
    <xsd:complexType name="diagnosticosType">
        <xsd:sequence>
            <xsd:element name="diagnostico" type="xsd:string" maxOccurs="unbounded"></xsd:element>
        </xsd:sequence>
    </xsd:complexType>
    <xsd:element name="respuesta">
        <xsd:complexType>
            <xsd:all>
                <xsd:element name="contenido" type="tns:contenidoType"></xsd:element>
                <xsd:element name="diagnosticos" type="tns:diagnosticosType" minOccurs="0"></xsd:element>
            </xsd:all>
        </xsd:complexType>
    </xsd:element>
</xsd:schema>

=== demianbarry/zonales/ZonalesSolrClient/src/java/com/zonales/solrclient/ZonalesSolrQueryRespuesta.xml
<?xml version="1.0" encoding="UTF-8"?>

<!--
    Document   : ZonalesSolrQueryRespuesta.xml
    Created on : 6 de octubre de 2009, 19:45
    Author     : fep
    Description:
        Purpose of the document follows.
-->

<ns0:respuesta  xmlns:xsi='http://www.w3.org/2001/XMLSchema-instance'
   xmlns:ns0='http://www.zonales.com.ar/schema/ZonalesSolrQueryResponse'
   xsi:schemaLocation='http://www.zonales.com.ar/schema/ZonalesSolrQueryResponse ZonalesSolrQueryRespuesta.xsd'>
    <ns0:contenido>
        <ns0:resultados>
            <ns0:resultado>
                <ns0:id></ns0:id>
            </ns0:resultado>
            <ns0:resultado>
                <ns0:id></ns0:id>
            </ns0:resultado>
            <ns0:resultado>
                <ns0:id></ns0:id>
            </ns0:resultado>
        </ns0:resultados>
    </ns0:contenido>
    <ns0:diagnosticos>
        <ns0:diagnostico></ns0:diagnostico>
        <ns0:diagnostico></ns0:diagnostico>
        <ns0:diagnostico></ns0:diagnostico>
    </ns0:diagnosticos>

</ns0:respuesta>
