=== demianbarry/zonales/src/XZone.xsd
<?xml version="1.0" encoding="UTF-8" ?>

<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

	<xs:simpleType name="url">
		<xs:restriction base="xs:string"></xs:restriction>
	</xs:simpleType>

	<xs:complexType name="linkType">
		<xs:sequence>
			<xs:element name="type" type="xs:string"></xs:element>
			<xs:element name="url" type="url"></xs:element>
		</xs:sequence>
	</xs:complexType>

	<xs:complexType name="linksType">
		<xs:sequence maxOccurs="unbounded">
			<xs:element name="link" type="linkType"></xs:element>
		</xs:sequence>
	</xs:complexType>

	<xs:complexType name="user">
		<xs:sequence>
			<xs:element name="id" type="xs:string" maxOccurs="1"
				minOccurs="1">
			</xs:element>
			<xs:element name="name" type="xs:string" maxOccurs="1"
				minOccurs="1">
			</xs:element>
			<xs:element name="url" type="url" maxOccurs="1" minOccurs="1">
			</xs:element>
			<xs:element name="category" type="xs:string" maxOccurs="1"
				minOccurs="0"></xs:element>
		</xs:sequence>
	</xs:complexType>

	<xs:complexType name="toUsersType">
		<xs:sequence maxOccurs="unbounded">
			<xs:element name="toUser" type="user"></xs:element>
		</xs:sequence>
	</xs:complexType>

	<xs:complexType name="actionType">
		<xs:sequence>
			<xs:element name="type" type="xs:string"></xs:element>
			<xs:element name="cant" type="xs:int"></xs:element>
		</xs:sequence>
	</xs:complexType>

	<xs:complexType name="actionsType">
		<xs:sequence maxOccurs="unbounded">
			<xs:element name="action" type="actionType"></xs:element>
		</xs:sequence>
	</xs:complexType>

	<xs:complexType name="tagsType">
		<xs:sequence maxOccurs="unbounded">
			<xs:element name="tag" type="xs:string"></xs:element>
		</xs:sequence>
	</xs:complexType>

	<xs:complexType name="postType">
		<xs:sequence>
			<xs:element name="source" type="xs:string" />
			<xs:element name="id" type="xs:string" />
			<xs:element name="from" type="user" />
			<xs:element name="toUsers" type="toUsersType" />
			<xs:element name="title" type="xs:string" />
			<xs:element name="text" type="xs:string" />
			<xs:element name="links" type="linksType" />
			<xs:element name="actions" type="actionsType" />
			<xs:element name="tags" type="tagsType" />
			<xs:element name="created" type="xs:dateTime" />
			<xs:element name="modified" type="xs:dateTime" />
            <xs:element name="relevance" type="xs:int" />
            <xs:element name="verbatim" type="xs:string"></xs:element>
        </xs:sequence>
	</xs:complexType>

	<xs:complexType name="postsType">
		<xs:sequence maxOccurs="unbounded">
			<xs:element name="post" type="postType" />
		</xs:sequence>
	</xs:complexType>

	<xs:element name="posts" type="postsType" />

</xs:schema>

=== demianbarry/zonales/newXMLDocument.xml
<posts xsi="http://www.w3.org/2001/XMLSchema-instance" noNamespaceSchemaLocation="http://200.69.225.53:30082/XZone.xsd">
    <post>
        <source>Facebook</source>
        <id>222136235762_10150106887765763</id>
        <fromUser>
            <name>Museo Municipal de Arte de Puerto Madryn</name>
            <category>Local business</category>
            <id>222136235762</id>
            <url>http://www.facebook.com/profile.php?id=222136235762</url>
        </fromUser>
        <title>Felicidades...</title>
        <text>Felicidades !!!!</text>
        <links>
            <link>
                <type>picture</type>
                <url>http://photos-e.ak.fbcdn.net/hphotos-ak-snc4/157014_10150106887755763_222136235762_8160956_5411477_s.jpg</url>
            </link>
            <link>
                <type>photo</type>
                <url>http://www.facebook.com/photo.php?fbid=10150106887755763&set=a.250053930762.184964.222136235762&type=1</url>
            </link>
        </links>
        <actions>
            <action>
                <type>like</type>
                <cant>3</cant>
            </action>
        </actions>
        <created>2010-12-24T14:51:06+0000</created>
        <modified>2010-12-24T14:51:06+0000</modified>
        <relevance>3</relevance>
        <verbatim><![CDATA[{
  "source":"Facebook",
  "id":"222136235762_10150106887765763",
  "fromUser":{
    "name":"Museo Municipal de Arte de Puerto Madryn",
    "category":"Local business",
    "id":"222136235762",
    "url":"http:\/\/www.facebook.com\/profile.php?id=222136235762"
  },
  "title":"Felicidades...",
  "text":"Felicidades !!!!",
  "links":[
    {
      "type":"picture",
      "url":"http:\/\/photos-e.ak.fbcdn.net\/hphotos-ak-snc4\/157014_10150106887755763_222136235762_8160956_5411477_s.jpg"
    },
    {
      "type":"photo",
      "url":"http:\/\/www.facebook.com\/photo.php?fbid=10150106887755763&set=a.250053930762.184964.222136235762&type=1"
    }
  ],
  "actions":[
    {
      "type":"like",
      "cant":3
    }
  ],
  "created":"2010-12-24T14:51:06+0000",
  "modified":"2010-12-24T14:51:06+0000",
  "relevance":3
}]]>
        </verbatim>
    </post>
    <post>
        <source>Facebook</source>
        <id>222136235762_10150104259985763</id>
        <fromUser>
            <name>Museo Municipal de Arte de Puerto Madryn</name>
            <category>Local business</category>
            <id>222136235762</id>
            <url>http://www.facebook.com/profile.php?id=222136235762</url>
        </fromUser>
        <title>El Museo Municipal de Arte los invita el próximo...</title>
        <text>El Museo Municipal de Arte los invita el próximo Miércoles 22 de Diciembre a las 20 hs a la inauguración del artista visual Emanuel Reyes, con la serie titulada: "TAUROMAQUIA EN PLATOS". Los esperamos a todos.</text>
        <links>
            <link>
                <type>picture</type>
                <url>http://photos-d.ak.fbcdn.net/hphotos-ak-ash1/164423_10150104259960763_222136235762_8115967_1827769_s.jpg</url>
            </link>
            <link>
                <type>photo</type>
                <url>http://www.facebook.com/photo.php?fbid=10150104259960763&set=a.250053930762.184964.222136235762&type=1</url>
            </link>
        </links>
        <actions>
            <action>
                <type>like</type>
                <cant>5</cant>
            </action>
            <action>
                <type>comment</type>
                <cant>2</cant>
            </action>
        </actions>
        <created>2010-12-19T21:15:05+0000</created>
        <modified>2010-12-20T23:48:27+0000</modified>
        <relevance>11</relevance>
        <verbatim><![CDATA[{
  "source":"Facebook",
  "id":"222136235762_10150104259985763",
  "fromUser":{
    "name":"Museo Municipal de Arte de Puerto Madryn",
    "category":"Local business",
    "id":"222136235762",
    "url":"http:\/\/www.facebook.com\/profile.php?id=222136235762"
  },
  "title":"El Museo Municipal de Arte los invita el pr\u00f3ximo...",
  "text":"El Museo Municipal de Arte los invita el pr\u00f3ximo Mi\u00e9rcoles 22 de Diciembre a las 20 hs a la inauguraci\u00f3n del artista visual Emanuel Reyes, con la serie titulada: \"TAUROMAQUIA EN PLATOS\". Los esperamos a todos.",
  "links":[
    {
      "type":"picture",
      "url":"http:\/\/photos-d.ak.fbcdn.net\/hphotos-ak-ash1\/164423_10150104259960763_222136235762_8115967_1827769_s.jpg"
    },
    {
      "type":"photo",
      "url":"http:\/\/www.facebook.com\/photo.php?fbid=10150104259960763&set=a.250053930762.184964.222136235762&type=1"
    }
  ],
  "actions":[
    {
      "type":"like",
      "cant":5
    },
    {
      "type":"comment",
      "cant":2
    }
  ],
  "created":"2010-12-19T21:15:05+0000",
  "modified":"2010-12-20T23:48:27+0000",
  "relevance":11
}]]>
        </verbatim>
    </post>
    <post>
        <source>Facebook</source>
        <id>199219160505_10150654776690506</id>
        <fromUser>
            <name>Julian Rodriguez</name>
            <id>100001083437655</id>
            <url>http://www.facebook.com/profile.php?id=100001083437655</url>
        </fromUser>
        <toUsers>
            <toUser>
                <name>LU17.com</name>
                <category>Website</category>
                <id>199219160505</id>
                <url>http://www.facebook.com/profile.php?id=199219160505</url>
            </toUser>
        </toUsers>
        <title>hay...</title>
        <text>hay clases?
        </text>
        <links/>
        <actions>
            <action>
                <type>like</type>
                <cant>1</cant>
            </action>
        </actions>
        <created>2011-06-10T14:49:10+0000</created>
        <modified>2011-06-10T14:49:10+0000</modified>
        <relevance>1</relevance>
        <verbatim><![CDATA[{
  "source":"Facebook",
  "id":"199219160505_10150654776690506",
  "fromUser":{
    "name":"Julian Rodriguez",
    "id":"100001083437655",
    "url":"http:\/\/www.facebook.com\/profile.php?id=100001083437655"
  },
  "toUsers":[
    {
      "name":"LU17.com",
      "category":"Website",
      "id":"199219160505",
      "url":"http:\/\/www.facebook.com\/profile.php?id=199219160505"
    }
  ],
  "title":"hay...",
  "text":"hay clases?\n",
  "links":[

  ],
  "actions":[
    {
      "type":"like",
      "cant":1
    }
  ],
  "created":"2011-06-10T14:49:10+0000",
  "modified":"2011-06-10T14:49:10+0000",
  "relevance":1
}]]>
        </verbatim>
    </post>
    <post>
        <source>Facebook</source>
        <id>199219160505_10150654772695506</id>
        <fromUser>
            <name>Ramón Cea</name>
            <id>1725691268</id>
            <url>http://www.facebook.com/profile.php?id=1725691268</url>
        </fromUser>
        <toUsers>
            <toUser>
                <name>LU17.com</name>
                <category>Website</category>
                <id>199219160505</id>
                <url>http://www.facebook.com/profile.php?id=199219160505</url>
            </toUser>
        </toUsers>
        <title>Hay o no hay clases hoy !...</title>
        <text>Hay o no hay clases hoy ! </text>
        <links/>
        <actions>
            <action>
                <type>like</type>
                <cant>1</cant>
            </action>
        </actions>
        <created>2011-06-10T14:45:24+0000</created>
        <modified>2011-06-10T14:45:24+0000</modified>
        <relevance>1</relevance>
        <verbatim><![CDATA[{
  "source":"Facebook",
  "id":"199219160505_10150654772695506",
  "fromUser":{
    "name":"Ram\u00f3n Cea",
    "id":"1725691268",
    "url":"http:\/\/www.facebook.com\/profile.php?id=1725691268"
  },
  "toUsers":[
    {
      "name":"LU17.com",
      "category":"Website",
      "id":"199219160505",
      "url":"http:\/\/www.facebook.com\/profile.php?id=199219160505"
    }
  ],
  "title":"Hay o no hay clases hoy !...",
  "text":"Hay o no hay clases hoy ! ",
  "links":[

  ],
  "actions":[
    {
      "type":"like",
      "cant":1
    }
  ],
  "created":"2011-06-10T14:45:24+0000",
  "modified":"2011-06-10T14:45:24+0000",
  "relevance":1
}]]>
        </verbatim>
    </post>
    <post>
        <source>Facebook</source>
        <id>365539206306_10150194388181307</id>
        <fromUser>
            <name>Silvia Andrea Bustos</name>
            <id>100000285451296</id>
            <url>http://www.facebook.com/profile.php?id=100000285451296</url>
        </fromUser>
        <toUsers>
            <toUser>
                <name>A.P.A.M. - Asociación Protectora de Animales de Puerto Madryn</name>
                <category>Non-profit organization</category>
                <id>365539206306</id>
                <url>http://www.facebook.com/profile.php?id=365539206306</url>
            </toUser>
        </toUsers>
        <title>hola gente, les comento algo , hace algun tiempo...</title>
        <text>hola gente, les comento algo , hace algun tiempo cuando descubri la perrita y sus cachorros del b. oeste en una cueva hay un basural como llendo para las quintas puedo asegurarles que hay cosas que se pueden reciclar y hacer cuchas para los perros del refugio y suele haber material para construccion que puede servir tambien , no esta de mas cartonear o como se diga ir a buscar a un basural si es para los pichis..... </text>
        <links/>
        <actions>
            <action>
                <type>like</type>
                <cant>2</cant>
            </action>
            <action>
                <type>comment</type>
                <cant>1</cant>
            </action>
        </actions>
        <created>2011-06-10T03:31:08+0000</created>
        <modified>2011-06-10T12:51:34+0000</modified>
        <relevance>5</relevance>
        <verbatim><![CDATA[{
  "source":"Facebook",
  "id":"365539206306_10150194388181307",
  "fromUser":{
    "name":"Silvia Andrea Bustos",
    "id":"100000285451296",
    "url":"http:\/\/www.facebook.com\/profile.php?id=100000285451296"
  },
  "toUsers":[
    {
